### ISSUE TITLE
How would you guys think if ss-uri-gen supports `get-ss-links` func on groups?

### ISSUE THREAD

**Issue by IceCodeNew** [database64128/shadowsocks-uri-generator#12]
Here is my use-case: A server behind NAT, running [`mmp-go`](https://github.com/Qv2ray/mmp-go) and proxying incoming traffic to several shadowsocks server by determining which password the client provide.
It seems to me that I have to treat each shadowsocks server as an individual user in `ss-uri-gen`'s database. So as to store different credentials.
Thus I have no idea how to export a full SS URL list consists of several shadowsocks servers. Only if we have the `get-ss-links` function works in the group context.

**Comment by database64128** [comment]
Each group is supposed to represent one endpoint (where the Shadowsocks server runs). Credential associations are user-group mappings. So you can have multiple nodes (direct connection to VPS, relays, etc) in the same group, that have the same endpoint and share the same credential for each user.

Let's say you have 3 Shadowsocks servers with 3 different passwords. All of them are also relayed by your single `mmp-go` instance on the same port. You'll want to create 3 groups. In each group, add 2 nodes, one for connecting directly to the VPS, another for connecting via the relay. Create a user for yourself and add the credentials to these groups. Now you can get your user's ss:// links that will cover all 6 nodes.

**Comment by IceCodeNew** [comment]
> Each group is supposed to represent one endpoint (where the Shadowsocks server runs). Credential associations are user-group mappings. So you can have multiple nodes (direct connection to VPS, relays, etc) in the same group, that have the same endpoint and share the same credential for each user.
> 
> Let's say you have 3 Shadowsocks servers with 3 different passwords. All of them are also relayed by your single `mmp-go` instance on the same port. You'll want to create 3 groups. In each group, add 2 nodes, one for connecting directly to the VPS, another for connecting via the relay. Create a user for yourself and add the credentials to these groups. Now you can get your user's ss:// links that will cover all 6 nodes.

I see. How come I missed that.
